sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

services:
  - mysql

language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - TEST_DIR=$TRAVIS_BUILD_DIR/test WCMF_BASE_DIR=$TRAVIS_BUILD_DIR

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar"
  - "java -jar selenium-server-standalone-2.48.2.jar &"
  - sleep 5

  - mysql -e 'CREATE DATABASE wcmf_testapp;'
  - composer self-update
  - composer install

  - cd $WCMF_BASE_DIR/build && ant generate && ant dist
  - chmod +x ../dist/vendor/phpunit/phpunit/phpunit

script:
  - cd $TEST_DIR &&  ../dist/vendor/phpunit/phpunit/phpunit --bootstrap bootstrap.php -c configuration.xml
